import Head from "next/head";
import Image from "next/image";
import plant1 from "../public/001-plant 1.png";
import plant2 from "../public/001-plant 2.png";
import plant3 from "../public/001-plant 3.png";
import plant4 from "../public/001-plant 4.png";
import image1 from "../public/image-1.png";
import image2 from "../public/image-2.png";
import image3 from "../public/image-3.png";
import image4 from "../public/image-4.png";
import Navbar from "../components/navbar";
import styles from "../styles/index.module.scss";

export default function Home() {
  const tinyPlants= [
    { id: 1, image:plant1 },

    { id: 2, image: plant2 },

    { id: 3, image: plant3 },

    { id: 4, image: plant4 },
  ];

  const images = [
    { bgImage: image1, id:1},
    { bgImage: image2, id: 2},
    { bgImage: image3, id: 3},
    { bgImage: image4, id: 4},
  ];

  return (
    <div>
      <Head>
        <title>Plant Shop</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.background}>
        <Navbar />
        <div className={styles.lets}>
          Lets find <br /> your love <br />{" "}
          <span className={styles.plant}>plants</span>
        </div>
        <div className={styles.add}>
          Add some color to your home, give it a <br /> little attention, the
          plants will<br /> accompany you quietly
        </div>
        <button className={styles.btn}>WATCH THE VIDEO</button>
       
        <div className={styles.plantsCon} >
          {tinyPlants.map((item, i) => (
            
          <Image className={styles[`plant${item.id}`]} src={item.image} alt=""key={i} />
            
          ))}
          </div>

    
      </main>

      <section className={styles.secondSection}>
        <button className={styles.servicebtn}>Try for service</button>
        <p className={styles.get}>GET A BEAUTIFUL HOME</p>
        <p className={styles.configure}>
          If you don’t know what plants you can add to the <br /> We can provide
          you with selected plants <br />
          And configure your space
        </p>

        <p className={styles.types}>4 types of plants </p>

        <div className={styles.lowerCon}>

          {images.map((image, i) => (
             <div className={styles.lowerImagesCon} key={i}>
               <Image src={image.bgImage} alt=""/>
             </div>
            
  ))}
        </div>
      </section>
    </div>
  );
}
